### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by maxkusnetsov** [SPoket/master-thesis#1]
- Списки
- Таблиц
- Заголовков

**Comment by maxkusnetsov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Отступы перед/после списков](https://trello.com/c/mk2UxVu6/11-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF%D1%8B-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%BE%D0%B2)

![](https://github.trello.services/images/mini-trello-icon.png) [Отступ от таблиц](https://trello.com/c/4tKRHyX0/18-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF-%D0%BE%D1%82-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86)

![](https://github.trello.services/images/mini-trello-icon.png) [Отступы заголовков](https://trello.com/c/Tzez56Wv/19-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF%D1%8B-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D0%B2)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Отступ от таблиц](https://trello.com/c/4tKRHyX0/18-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF-%D0%BE%D1%82-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Отступы заголовков](https://trello.com/c/Tzez56Wv/19-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF%D1%8B-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D0%B2)

**Comment by maxkusnetsov** [comment]
Fix in https://github.com/SPoket/master-thesis/commit/61d7a277e6e53b204cb2e57fb4e493b81fbc888e
