### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by maxkusnetsov** [SPoket/master-thesis#2]

**Comment by maxkusnetsov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Уточнить, исправить стиль исходного кода](https://trello.com/c/kxKOoUa5/17-%D1%83%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D1%82%D1%8C-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D0%B8%D0%BB%D1%8C-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%B4%D0%B0)

![](https://github.trello.services/images/mini-trello-icon.png) [Удалить информацию о реле](https://trello.com/c/66RMtVyF/16-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E-%D0%BE-%D1%80%D0%B5%D0%BB%D0%B5)

![](https://github.trello.services/images/mini-trello-icon.png) [section в верхнем регистре](https://trello.com/c/gZaGw5eZ/15-section-%D0%B2-%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%BC-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B5)

![](https://github.trello.services/images/mini-trello-icon.png) [Исправить орфографию, синтаксис, ошибки](https://trello.com/c/XM77ehNh/13-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8E-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

![](https://github.trello.services/images/mini-trello-icon.png) [Дописать TODO и дополнения](https://trello.com/c/dZMDDDBW/12-%D0%B4%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-todo-%D0%B8-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Удалить информацию о реле](https://trello.com/c/66RMtVyF/16-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E-%D0%BE-%D1%80%D0%B5%D0%BB%D0%B5)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [section в верхнем регистре](https://trello.com/c/gZaGw5eZ/15-section-%D0%B2-%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%BC-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B5)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Исправить орфографию, синтаксис, ошибки](https://trello.com/c/XM77ehNh/13-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8E-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

**Comment by SPoket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Дописать TODO и дополнения](https://trello.com/c/dZMDDDBW/12-%D0%B4%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-todo-%D0%B8-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F)

**Comment by maxkusnetsov** [comment]
Fix in https://github.com/SPoket/master-thesis/commit/61d7a277e6e53b204cb2e57fb4e493b81fbc888e
